package model.modelType;

public enum SSEType {
	CREATECOMMENT, DELETECOMMENT, CREATEPOST, CREATEPOSTINCOMMUNITY, DELETEPOST, DELETEPOSTFROMCOMMUNITY,
	LIKEPOST, CANCELLIKEPOST, COLLECTPOST, CANCELCOLLECTPOST, JOINACTIVITY, LEAVEACTIVITY,
	JOINCOMMUNITY, LEAVECOMMUITY, DELETECOMMUNITY, LIKECOMMENT, CANCELLIKECOMMENT, FOLLOW, 
	CONNECT, DISCONNECT, COMMUNITYOWNERCREATED, APPLICATIONREJECTED, APPLICATIONPASSED;
	
	public String toString() {
		return this.name();
	}
}
